# Generated by Django 3.0.5 on 2020-05-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200504_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentoffer',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
