# Generated by Django 3.0.5 on 2020-06-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200505_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.IntegerField(),
        ),
    ]
