# Generated by Django 3.0.5 on 2020-06-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200617_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentoffer',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentoffer',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
